### ISSUE TITLE
Additional field for slug

### ISSUE THREAD

**Issue by icgdoug** [Hambern/octobercms.company#13]
Is it possible to add a slug field like the Rainlab Blog plugin.

This would allow for keyword based URLs rather than navigating by the ID to view individual services, people, etc..

**Comment by hambern** [comment]
Yes... I think a future redisign of this should include slugs. The problem is that it could break peoples already finished websites. So if i do, i have to point this out clearly

**Comment by icgdoug** [comment]
Thanks for your swift response. We are evaluating October CMS as a viable alternative to WordPress. Your plugin fills a gap for a lot of the corporate site functions that we need but SEO is key so the slug/permalink URL style is critical for our need. Great work on this plugin so far.

**Comment by hambern** [comment]
Thanks. It's acctually a really simple plugin i made when I wasn't that
good with the CMS. With the builder-plugin this can be made in a few hours
:)
fre 5 maj 2017 kl. 11:33 skrev Doug Mouncey <notifications@github.com>:

**Comment by hambern** [comment]
I've now restarted this plugin with my current know-how. Will att slugs on everything and not aim it only at companies but also organizations :)

**Comment by TimFoerster** [comment]
@Hambern do you need some help for this plugin? Because I require some links to services as well :)

**Comment by hambern** [comment]
I have restarted this project as a Hambern.Aboutus plugin now. It will be better. I'm not sure what to do with this though. I think i will leave it in the current state, maybe fix some small things and then leave it to it's destiny.

We can make such a link. Though: you can pretty easily add those type of things with your own plugin extension. [http://octobercms.com/docs/plugin/extending](http://octobercms.com/docs/plugin/extending). That way we can keep the plugin core pretty basic, and if you want to add more things you can that suits your needs.

I often do this. I've created an extension for the blog-plugin to be able to connect files to the posts as an example :)

**Comment by TimFoerster** [comment]
Btw. Can you add a hook to this git repo for ocms updates? https://octobercms.com/help/site/authors#managing-plugins

Cheers

**Comment by hambern** [comment]
Well... Could you explain more. I thought I had added that...

**Comment by TimFoerster** [comment]
On ocms: https://octobercms.com/account/author/dashboard, click on the plugin, updates, click on _Display Update URL_, copy the url. 
Go on Github in this project, navigate to settings -> Webhooks -> Add webhook -> paste url -> add webhook.

**Comment by ametad** [comment]
Thank you for your work already, I use this plugin of yours a lot! You write it is 'a simple' plugin, but that is what I like about it. It is therefore very flexible. The components just inject the data into the pages and I can just use what is needed.

The 'slug' functionality would create nice normal- and good SEO urls.

If I would make use of a tag filter from an url parameter, perhaps that can be done like the following:

![image](https://user-images.githubusercontent.com/1582541/28247027-df8cc02a-6a28-11e7-8117-46b573948c27.png)

![image](https://user-images.githubusercontent.com/1582541/28247037-14093f72-6a29-11e7-80f3-ebc4f37e863f.png)

~~But now it could contain spaces, capitals or other not wanted characters in the url. Because it uses the 'name' attribute to query the database. A 'slug' would take care of this problem.~~ 
(I just find out looking at the code it is not correct assumed of me..)

The pictures show how I would like to make use of tags (and their slug value) in the urls. Kind of like it is used in the Blog plugin of Rainlab (https://github.com/rainlab/blog-plugin)

If you want I could help you by sending you an PR. Is that helpful, or perhaps not because of pending work of your own?

**Comment by hambern** [comment]
Sorry... But I have dropped this project now. This was my first real project and I've learned much while creating this. I have started making a new plugin like this, but a lot better as that was easier than making all the changes backwards compatible. It simply wasn't possible. So... basically, anyone who wants to countinue on this plugin can have it

**Comment by ametad** [comment]
Hi Hambern,
A pitty, but understandable... 
I am willing to continue your plugin for maintenance. Is that something we could discuss?

**Comment by hambern** [comment]
Absolutely. Can invite you to the project

**Comment by ametad** [comment]
@Hambern Thank you!

**Comment by ametad** [comment]
The 'slug' feature will be implemented soon, as I am a contributor now. But please be patient because I have to test a few things first.
